// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: company.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "company";

export interface Company {
  id: string;
  name: string;
  description: string;
  website: string;
  industry: string;
  logoUrl: string;
  location: string;
  employeeCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCompanyRequest {
  name: string;
  description: string;
  website: string;
  industry: string;
  logoUrl: string;
  location: string;
  employeeCount: number;
}

export interface GetCompanyRequest {
  id: string;
}

export interface ListCompaniesRequest {
  page: number;
  limit: number;
  industry: string;
}

export interface ListCompaniesResponse {
  companies: Company[];
  total: number;
}

export interface UpdateCompanyRequest {
  id: string;
  name: string;
  description: string;
  website: string;
  industry: string;
  logoUrl: string;
  location: string;
  employeeCount: number;
}

export interface DeleteCompanyRequest {
  id: string;
}

export interface DeleteCompanyResponse {
  success: boolean;
}

export interface CompanyResponse {
  company: Company | undefined;
}

export interface Review {
  id: string;
  companyId: string;
  userId: string;
  rating: number;
  comment: string;
  createdAt: string;
  positionTitle: string;
}

export interface CreateReviewRequest {
  companyId: string;
  userId: string;
  rating: number;
  comment: string;
  positionTitle: string;
}

export interface ReviewResponse {
  review: Review | undefined;
}

export interface ListReviewsRequest {
  companyId: string;
  page: number;
  limit: number;
}

export interface ListReviewsResponse {
  reviews: Review[];
  total: number;
  averageRating: number;
}

function createBaseCompany(): Company {
  return {
    id: "",
    name: "",
    description: "",
    website: "",
    industry: "",
    logoUrl: "",
    location: "",
    employeeCount: 0,
    createdAt: "",
    updatedAt: "",
  };
}

export const Company: MessageFns<Company> = {
  encode(message: Company, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.website !== "") {
      writer.uint32(34).string(message.website);
    }
    if (message.industry !== "") {
      writer.uint32(42).string(message.industry);
    }
    if (message.logoUrl !== "") {
      writer.uint32(50).string(message.logoUrl);
    }
    if (message.location !== "") {
      writer.uint32(58).string(message.location);
    }
    if (message.employeeCount !== 0) {
      writer.uint32(64).int32(message.employeeCount);
    }
    if (message.createdAt !== "") {
      writer.uint32(74).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(82).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Company {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompany();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.website = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.industry = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.logoUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.employeeCount = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Company {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      website: isSet(object.website) ? globalThis.String(object.website) : "",
      industry: isSet(object.industry) ? globalThis.String(object.industry) : "",
      logoUrl: isSet(object.logoUrl)
        ? globalThis.String(object.logoUrl)
        : isSet(object.logo_url)
        ? globalThis.String(object.logo_url)
        : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      employeeCount: isSet(object.employeeCount)
        ? globalThis.Number(object.employeeCount)
        : isSet(object.employee_count)
        ? globalThis.Number(object.employee_count)
        : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: Company): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    if (message.industry !== "") {
      obj.industry = message.industry;
    }
    if (message.logoUrl !== "") {
      obj.logoUrl = message.logoUrl;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.employeeCount !== 0) {
      obj.employeeCount = Math.round(message.employeeCount);
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Company>, I>>(base?: I): Company {
    return Company.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Company>, I>>(object: I): Company {
    const message = createBaseCompany();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.website = object.website ?? "";
    message.industry = object.industry ?? "";
    message.logoUrl = object.logoUrl ?? "";
    message.location = object.location ?? "";
    message.employeeCount = object.employeeCount ?? 0;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseCreateCompanyRequest(): CreateCompanyRequest {
  return { name: "", description: "", website: "", industry: "", logoUrl: "", location: "", employeeCount: 0 };
}

export const CreateCompanyRequest: MessageFns<CreateCompanyRequest> = {
  encode(message: CreateCompanyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.website !== "") {
      writer.uint32(26).string(message.website);
    }
    if (message.industry !== "") {
      writer.uint32(34).string(message.industry);
    }
    if (message.logoUrl !== "") {
      writer.uint32(42).string(message.logoUrl);
    }
    if (message.location !== "") {
      writer.uint32(50).string(message.location);
    }
    if (message.employeeCount !== 0) {
      writer.uint32(56).int32(message.employeeCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCompanyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCompanyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.website = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.industry = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.logoUrl = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.employeeCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCompanyRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      website: isSet(object.website) ? globalThis.String(object.website) : "",
      industry: isSet(object.industry) ? globalThis.String(object.industry) : "",
      logoUrl: isSet(object.logoUrl)
        ? globalThis.String(object.logoUrl)
        : isSet(object.logo_url)
        ? globalThis.String(object.logo_url)
        : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      employeeCount: isSet(object.employeeCount)
        ? globalThis.Number(object.employeeCount)
        : isSet(object.employee_count)
        ? globalThis.Number(object.employee_count)
        : 0,
    };
  },

  toJSON(message: CreateCompanyRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    if (message.industry !== "") {
      obj.industry = message.industry;
    }
    if (message.logoUrl !== "") {
      obj.logoUrl = message.logoUrl;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.employeeCount !== 0) {
      obj.employeeCount = Math.round(message.employeeCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCompanyRequest>, I>>(base?: I): CreateCompanyRequest {
    return CreateCompanyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCompanyRequest>, I>>(object: I): CreateCompanyRequest {
    const message = createBaseCreateCompanyRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.website = object.website ?? "";
    message.industry = object.industry ?? "";
    message.logoUrl = object.logoUrl ?? "";
    message.location = object.location ?? "";
    message.employeeCount = object.employeeCount ?? 0;
    return message;
  },
};

function createBaseGetCompanyRequest(): GetCompanyRequest {
  return { id: "" };
}

export const GetCompanyRequest: MessageFns<GetCompanyRequest> = {
  encode(message: GetCompanyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCompanyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCompanyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCompanyRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetCompanyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCompanyRequest>, I>>(base?: I): GetCompanyRequest {
    return GetCompanyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCompanyRequest>, I>>(object: I): GetCompanyRequest {
    const message = createBaseGetCompanyRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseListCompaniesRequest(): ListCompaniesRequest {
  return { page: 0, limit: 0, industry: "" };
}

export const ListCompaniesRequest: MessageFns<ListCompaniesRequest> = {
  encode(message: ListCompaniesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.industry !== "") {
      writer.uint32(26).string(message.industry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCompaniesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCompaniesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.industry = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCompaniesRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      industry: isSet(object.industry) ? globalThis.String(object.industry) : "",
    };
  },

  toJSON(message: ListCompaniesRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.industry !== "") {
      obj.industry = message.industry;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCompaniesRequest>, I>>(base?: I): ListCompaniesRequest {
    return ListCompaniesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCompaniesRequest>, I>>(object: I): ListCompaniesRequest {
    const message = createBaseListCompaniesRequest();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.industry = object.industry ?? "";
    return message;
  },
};

function createBaseListCompaniesResponse(): ListCompaniesResponse {
  return { companies: [], total: 0 };
}

export const ListCompaniesResponse: MessageFns<ListCompaniesResponse> = {
  encode(message: ListCompaniesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.companies) {
      Company.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCompaniesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCompaniesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.companies.push(Company.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCompaniesResponse {
    return {
      companies: globalThis.Array.isArray(object?.companies)
        ? object.companies.map((e: any) => Company.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: ListCompaniesResponse): unknown {
    const obj: any = {};
    if (message.companies?.length) {
      obj.companies = message.companies.map((e) => Company.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCompaniesResponse>, I>>(base?: I): ListCompaniesResponse {
    return ListCompaniesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCompaniesResponse>, I>>(object: I): ListCompaniesResponse {
    const message = createBaseListCompaniesResponse();
    message.companies = object.companies?.map((e) => Company.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseUpdateCompanyRequest(): UpdateCompanyRequest {
  return { id: "", name: "", description: "", website: "", industry: "", logoUrl: "", location: "", employeeCount: 0 };
}

export const UpdateCompanyRequest: MessageFns<UpdateCompanyRequest> = {
  encode(message: UpdateCompanyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.website !== "") {
      writer.uint32(34).string(message.website);
    }
    if (message.industry !== "") {
      writer.uint32(42).string(message.industry);
    }
    if (message.logoUrl !== "") {
      writer.uint32(50).string(message.logoUrl);
    }
    if (message.location !== "") {
      writer.uint32(58).string(message.location);
    }
    if (message.employeeCount !== 0) {
      writer.uint32(64).int32(message.employeeCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCompanyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCompanyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.website = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.industry = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.logoUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.employeeCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateCompanyRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      website: isSet(object.website) ? globalThis.String(object.website) : "",
      industry: isSet(object.industry) ? globalThis.String(object.industry) : "",
      logoUrl: isSet(object.logoUrl)
        ? globalThis.String(object.logoUrl)
        : isSet(object.logo_url)
        ? globalThis.String(object.logo_url)
        : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      employeeCount: isSet(object.employeeCount)
        ? globalThis.Number(object.employeeCount)
        : isSet(object.employee_count)
        ? globalThis.Number(object.employee_count)
        : 0,
    };
  },

  toJSON(message: UpdateCompanyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    if (message.industry !== "") {
      obj.industry = message.industry;
    }
    if (message.logoUrl !== "") {
      obj.logoUrl = message.logoUrl;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.employeeCount !== 0) {
      obj.employeeCount = Math.round(message.employeeCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateCompanyRequest>, I>>(base?: I): UpdateCompanyRequest {
    return UpdateCompanyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateCompanyRequest>, I>>(object: I): UpdateCompanyRequest {
    const message = createBaseUpdateCompanyRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.website = object.website ?? "";
    message.industry = object.industry ?? "";
    message.logoUrl = object.logoUrl ?? "";
    message.location = object.location ?? "";
    message.employeeCount = object.employeeCount ?? 0;
    return message;
  },
};

function createBaseDeleteCompanyRequest(): DeleteCompanyRequest {
  return { id: "" };
}

export const DeleteCompanyRequest: MessageFns<DeleteCompanyRequest> = {
  encode(message: DeleteCompanyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCompanyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCompanyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCompanyRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteCompanyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteCompanyRequest>, I>>(base?: I): DeleteCompanyRequest {
    return DeleteCompanyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteCompanyRequest>, I>>(object: I): DeleteCompanyRequest {
    const message = createBaseDeleteCompanyRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteCompanyResponse(): DeleteCompanyResponse {
  return { success: false };
}

export const DeleteCompanyResponse: MessageFns<DeleteCompanyResponse> = {
  encode(message: DeleteCompanyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCompanyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCompanyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCompanyResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeleteCompanyResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteCompanyResponse>, I>>(base?: I): DeleteCompanyResponse {
    return DeleteCompanyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteCompanyResponse>, I>>(object: I): DeleteCompanyResponse {
    const message = createBaseDeleteCompanyResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseCompanyResponse(): CompanyResponse {
  return { company: undefined };
}

export const CompanyResponse: MessageFns<CompanyResponse> = {
  encode(message: CompanyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.company !== undefined) {
      Company.encode(message.company, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompanyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompanyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.company = Company.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompanyResponse {
    return { company: isSet(object.company) ? Company.fromJSON(object.company) : undefined };
  },

  toJSON(message: CompanyResponse): unknown {
    const obj: any = {};
    if (message.company !== undefined) {
      obj.company = Company.toJSON(message.company);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompanyResponse>, I>>(base?: I): CompanyResponse {
    return CompanyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompanyResponse>, I>>(object: I): CompanyResponse {
    const message = createBaseCompanyResponse();
    message.company = (object.company !== undefined && object.company !== null)
      ? Company.fromPartial(object.company)
      : undefined;
    return message;
  },
};

function createBaseReview(): Review {
  return { id: "", companyId: "", userId: "", rating: 0, comment: "", createdAt: "", positionTitle: "" };
}

export const Review: MessageFns<Review> = {
  encode(message: Review, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.companyId !== "") {
      writer.uint32(18).string(message.companyId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.rating !== 0) {
      writer.uint32(32).int32(message.rating);
    }
    if (message.comment !== "") {
      writer.uint32(42).string(message.comment);
    }
    if (message.createdAt !== "") {
      writer.uint32(50).string(message.createdAt);
    }
    if (message.positionTitle !== "") {
      writer.uint32(58).string(message.positionTitle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Review {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReview();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.rating = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.comment = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.positionTitle = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Review {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      rating: isSet(object.rating) ? globalThis.Number(object.rating) : 0,
      comment: isSet(object.comment) ? globalThis.String(object.comment) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      positionTitle: isSet(object.positionTitle)
        ? globalThis.String(object.positionTitle)
        : isSet(object.position_title)
        ? globalThis.String(object.position_title)
        : "",
    };
  },

  toJSON(message: Review): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.rating !== 0) {
      obj.rating = Math.round(message.rating);
    }
    if (message.comment !== "") {
      obj.comment = message.comment;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.positionTitle !== "") {
      obj.positionTitle = message.positionTitle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Review>, I>>(base?: I): Review {
    return Review.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Review>, I>>(object: I): Review {
    const message = createBaseReview();
    message.id = object.id ?? "";
    message.companyId = object.companyId ?? "";
    message.userId = object.userId ?? "";
    message.rating = object.rating ?? 0;
    message.comment = object.comment ?? "";
    message.createdAt = object.createdAt ?? "";
    message.positionTitle = object.positionTitle ?? "";
    return message;
  },
};

function createBaseCreateReviewRequest(): CreateReviewRequest {
  return { companyId: "", userId: "", rating: 0, comment: "", positionTitle: "" };
}

export const CreateReviewRequest: MessageFns<CreateReviewRequest> = {
  encode(message: CreateReviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.companyId !== "") {
      writer.uint32(10).string(message.companyId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.rating !== 0) {
      writer.uint32(24).int32(message.rating);
    }
    if (message.comment !== "") {
      writer.uint32(34).string(message.comment);
    }
    if (message.positionTitle !== "") {
      writer.uint32(42).string(message.positionTitle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateReviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rating = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.comment = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.positionTitle = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateReviewRequest {
    return {
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      rating: isSet(object.rating) ? globalThis.Number(object.rating) : 0,
      comment: isSet(object.comment) ? globalThis.String(object.comment) : "",
      positionTitle: isSet(object.positionTitle)
        ? globalThis.String(object.positionTitle)
        : isSet(object.position_title)
        ? globalThis.String(object.position_title)
        : "",
    };
  },

  toJSON(message: CreateReviewRequest): unknown {
    const obj: any = {};
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.rating !== 0) {
      obj.rating = Math.round(message.rating);
    }
    if (message.comment !== "") {
      obj.comment = message.comment;
    }
    if (message.positionTitle !== "") {
      obj.positionTitle = message.positionTitle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateReviewRequest>, I>>(base?: I): CreateReviewRequest {
    return CreateReviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateReviewRequest>, I>>(object: I): CreateReviewRequest {
    const message = createBaseCreateReviewRequest();
    message.companyId = object.companyId ?? "";
    message.userId = object.userId ?? "";
    message.rating = object.rating ?? 0;
    message.comment = object.comment ?? "";
    message.positionTitle = object.positionTitle ?? "";
    return message;
  },
};

function createBaseReviewResponse(): ReviewResponse {
  return { review: undefined };
}

export const ReviewResponse: MessageFns<ReviewResponse> = {
  encode(message: ReviewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.review !== undefined) {
      Review.encode(message.review, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReviewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReviewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.review = Review.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReviewResponse {
    return { review: isSet(object.review) ? Review.fromJSON(object.review) : undefined };
  },

  toJSON(message: ReviewResponse): unknown {
    const obj: any = {};
    if (message.review !== undefined) {
      obj.review = Review.toJSON(message.review);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReviewResponse>, I>>(base?: I): ReviewResponse {
    return ReviewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReviewResponse>, I>>(object: I): ReviewResponse {
    const message = createBaseReviewResponse();
    message.review = (object.review !== undefined && object.review !== null)
      ? Review.fromPartial(object.review)
      : undefined;
    return message;
  },
};

function createBaseListReviewsRequest(): ListReviewsRequest {
  return { companyId: "", page: 0, limit: 0 };
}

export const ListReviewsRequest: MessageFns<ListReviewsRequest> = {
  encode(message: ListReviewsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.companyId !== "") {
      writer.uint32(10).string(message.companyId);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListReviewsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListReviewsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListReviewsRequest {
    return {
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListReviewsRequest): unknown {
    const obj: any = {};
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListReviewsRequest>, I>>(base?: I): ListReviewsRequest {
    return ListReviewsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListReviewsRequest>, I>>(object: I): ListReviewsRequest {
    const message = createBaseListReviewsRequest();
    message.companyId = object.companyId ?? "";
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListReviewsResponse(): ListReviewsResponse {
  return { reviews: [], total: 0, averageRating: 0 };
}

export const ListReviewsResponse: MessageFns<ListReviewsResponse> = {
  encode(message: ListReviewsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.reviews) {
      Review.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    if (message.averageRating !== 0) {
      writer.uint32(25).double(message.averageRating);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListReviewsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListReviewsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reviews.push(Review.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.averageRating = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListReviewsResponse {
    return {
      reviews: globalThis.Array.isArray(object?.reviews) ? object.reviews.map((e: any) => Review.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      averageRating: isSet(object.averageRating)
        ? globalThis.Number(object.averageRating)
        : isSet(object.average_rating)
        ? globalThis.Number(object.average_rating)
        : 0,
    };
  },

  toJSON(message: ListReviewsResponse): unknown {
    const obj: any = {};
    if (message.reviews?.length) {
      obj.reviews = message.reviews.map((e) => Review.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.averageRating !== 0) {
      obj.averageRating = message.averageRating;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListReviewsResponse>, I>>(base?: I): ListReviewsResponse {
    return ListReviewsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListReviewsResponse>, I>>(object: I): ListReviewsResponse {
    const message = createBaseListReviewsResponse();
    message.reviews = object.reviews?.map((e) => Review.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.averageRating = object.averageRating ?? 0;
    return message;
  },
};

export type CompanyServiceService = typeof CompanyServiceService;
export const CompanyServiceService = {
  createCompany: {
    path: "/company.CompanyService/CreateCompany" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateCompanyRequest): Buffer => Buffer.from(CreateCompanyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateCompanyRequest => CreateCompanyRequest.decode(value),
    responseSerialize: (value: CompanyResponse): Buffer => Buffer.from(CompanyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CompanyResponse => CompanyResponse.decode(value),
  },
  getCompany: {
    path: "/company.CompanyService/GetCompany" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCompanyRequest): Buffer => Buffer.from(GetCompanyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCompanyRequest => GetCompanyRequest.decode(value),
    responseSerialize: (value: CompanyResponse): Buffer => Buffer.from(CompanyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CompanyResponse => CompanyResponse.decode(value),
  },
  listCompanies: {
    path: "/company.CompanyService/ListCompanies" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListCompaniesRequest): Buffer => Buffer.from(ListCompaniesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListCompaniesRequest => ListCompaniesRequest.decode(value),
    responseSerialize: (value: ListCompaniesResponse): Buffer =>
      Buffer.from(ListCompaniesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListCompaniesResponse => ListCompaniesResponse.decode(value),
  },
  updateCompany: {
    path: "/company.CompanyService/UpdateCompany" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateCompanyRequest): Buffer => Buffer.from(UpdateCompanyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateCompanyRequest => UpdateCompanyRequest.decode(value),
    responseSerialize: (value: CompanyResponse): Buffer => Buffer.from(CompanyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CompanyResponse => CompanyResponse.decode(value),
  },
  deleteCompany: {
    path: "/company.CompanyService/DeleteCompany" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteCompanyRequest): Buffer => Buffer.from(DeleteCompanyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteCompanyRequest => DeleteCompanyRequest.decode(value),
    responseSerialize: (value: DeleteCompanyResponse): Buffer =>
      Buffer.from(DeleteCompanyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteCompanyResponse => DeleteCompanyResponse.decode(value),
  },
  createReview: {
    path: "/company.CompanyService/CreateReview" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateReviewRequest): Buffer => Buffer.from(CreateReviewRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateReviewRequest => CreateReviewRequest.decode(value),
    responseSerialize: (value: ReviewResponse): Buffer => Buffer.from(ReviewResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReviewResponse => ReviewResponse.decode(value),
  },
  listReviews: {
    path: "/company.CompanyService/ListReviews" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListReviewsRequest): Buffer => Buffer.from(ListReviewsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListReviewsRequest => ListReviewsRequest.decode(value),
    responseSerialize: (value: ListReviewsResponse): Buffer => Buffer.from(ListReviewsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListReviewsResponse => ListReviewsResponse.decode(value),
  },
} as const;

export interface CompanyServiceServer extends UntypedServiceImplementation {
  createCompany: handleUnaryCall<CreateCompanyRequest, CompanyResponse>;
  getCompany: handleUnaryCall<GetCompanyRequest, CompanyResponse>;
  listCompanies: handleUnaryCall<ListCompaniesRequest, ListCompaniesResponse>;
  updateCompany: handleUnaryCall<UpdateCompanyRequest, CompanyResponse>;
  deleteCompany: handleUnaryCall<DeleteCompanyRequest, DeleteCompanyResponse>;
  createReview: handleUnaryCall<CreateReviewRequest, ReviewResponse>;
  listReviews: handleUnaryCall<ListReviewsRequest, ListReviewsResponse>;
}

export interface CompanyServiceClient extends Client {
  createCompany(
    request: CreateCompanyRequest,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  createCompany(
    request: CreateCompanyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  createCompany(
    request: CreateCompanyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  getCompany(
    request: GetCompanyRequest,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  getCompany(
    request: GetCompanyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  getCompany(
    request: GetCompanyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  listCompanies(
    request: ListCompaniesRequest,
    callback: (error: ServiceError | null, response: ListCompaniesResponse) => void,
  ): ClientUnaryCall;
  listCompanies(
    request: ListCompaniesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListCompaniesResponse) => void,
  ): ClientUnaryCall;
  listCompanies(
    request: ListCompaniesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListCompaniesResponse) => void,
  ): ClientUnaryCall;
  updateCompany(
    request: UpdateCompanyRequest,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  updateCompany(
    request: UpdateCompanyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  updateCompany(
    request: UpdateCompanyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CompanyResponse) => void,
  ): ClientUnaryCall;
  deleteCompany(
    request: DeleteCompanyRequest,
    callback: (error: ServiceError | null, response: DeleteCompanyResponse) => void,
  ): ClientUnaryCall;
  deleteCompany(
    request: DeleteCompanyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DeleteCompanyResponse) => void,
  ): ClientUnaryCall;
  deleteCompany(
    request: DeleteCompanyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DeleteCompanyResponse) => void,
  ): ClientUnaryCall;
  createReview(
    request: CreateReviewRequest,
    callback: (error: ServiceError | null, response: ReviewResponse) => void,
  ): ClientUnaryCall;
  createReview(
    request: CreateReviewRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReviewResponse) => void,
  ): ClientUnaryCall;
  createReview(
    request: CreateReviewRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReviewResponse) => void,
  ): ClientUnaryCall;
  listReviews(
    request: ListReviewsRequest,
    callback: (error: ServiceError | null, response: ListReviewsResponse) => void,
  ): ClientUnaryCall;
  listReviews(
    request: ListReviewsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListReviewsResponse) => void,
  ): ClientUnaryCall;
  listReviews(
    request: ListReviewsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListReviewsResponse) => void,
  ): ClientUnaryCall;
}

export const CompanyServiceClient = makeGenericClientConstructor(
  CompanyServiceService,
  "company.CompanyService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CompanyServiceClient;
  service: typeof CompanyServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
