// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: job.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "job";

export interface Job {
  id: string;
  companyId: string;
  postedByUserId: string;
  title: string;
  description: string;
  location: string;
  salaryRange: string;
  /** FULL_TIME, PART_TIME, CONTRACT, REMOTE */
  jobType: string;
  /** JUNIOR, MID, SENIOR, LEAD */
  experienceLevel: string;
  skills: string[];
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Application {
  id: string;
  jobId: string;
  userId: string;
  coverLetter: string;
  resumeUrl: string;
  /** PENDING, REVIEWED, ACCEPTED, REJECTED */
  status: string;
  createdAt: string;
}

export interface CreateJobRequest {
  companyId: string;
  postedByUserId: string;
  title: string;
  description: string;
  location: string;
  salaryRange: string;
  jobType: string;
  experienceLevel: string;
  skills: string[];
}

export interface GetJobRequest {
  id: string;
}

export interface ListJobsRequest {
  page: number;
  limit: number;
  jobType: string;
  experienceLevel: string;
  location: string;
  postedByUserId: string;
  companyId: string;
}

export interface ListJobsByCompanyRequest {
  companyId: string;
  page: number;
  limit: number;
}

export interface ListJobsResponse {
  jobs: Job[];
  total: number;
}

export interface UpdateJobRequest {
  id: string;
  title: string;
  description: string;
  location: string;
  salaryRange: string;
  jobType: string;
  experienceLevel: string;
  skills: string[];
  isActive: boolean;
}

export interface DeleteJobRequest {
  id: string;
}

export interface DeleteJobResponse {
  success: boolean;
}

export interface JobResponse {
  job: Job | undefined;
}

export interface ApplyToJobRequest {
  jobId: string;
  userId: string;
  coverLetter: string;
  resumeUrl: string;
}

export interface ApplicationResponse {
  application: Application | undefined;
}

export interface ListApplicationsByJobRequest {
  jobId: string;
  page: number;
  limit: number;
}

export interface ListApplicationsByUserRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface ListApplicationsResponse {
  applications: Application[];
  total: number;
}

function createBaseJob(): Job {
  return {
    id: "",
    companyId: "",
    postedByUserId: "",
    title: "",
    description: "",
    location: "",
    salaryRange: "",
    jobType: "",
    experienceLevel: "",
    skills: [],
    isActive: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const Job: MessageFns<Job> = {
  encode(message: Job, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.companyId !== "") {
      writer.uint32(18).string(message.companyId);
    }
    if (message.postedByUserId !== "") {
      writer.uint32(26).string(message.postedByUserId);
    }
    if (message.title !== "") {
      writer.uint32(34).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(42).string(message.description);
    }
    if (message.location !== "") {
      writer.uint32(50).string(message.location);
    }
    if (message.salaryRange !== "") {
      writer.uint32(58).string(message.salaryRange);
    }
    if (message.jobType !== "") {
      writer.uint32(66).string(message.jobType);
    }
    if (message.experienceLevel !== "") {
      writer.uint32(74).string(message.experienceLevel);
    }
    for (const v of message.skills) {
      writer.uint32(82).string(v!);
    }
    if (message.isActive !== false) {
      writer.uint32(88).bool(message.isActive);
    }
    if (message.createdAt !== "") {
      writer.uint32(98).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(106).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Job {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJob();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.postedByUserId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.salaryRange = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.jobType = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.experienceLevel = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.skills.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Job {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      postedByUserId: isSet(object.postedByUserId)
        ? globalThis.String(object.postedByUserId)
        : isSet(object.posted_by_user_id)
        ? globalThis.String(object.posted_by_user_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      salaryRange: isSet(object.salaryRange)
        ? globalThis.String(object.salaryRange)
        : isSet(object.salary_range)
        ? globalThis.String(object.salary_range)
        : "",
      jobType: isSet(object.jobType)
        ? globalThis.String(object.jobType)
        : isSet(object.job_type)
        ? globalThis.String(object.job_type)
        : "",
      experienceLevel: isSet(object.experienceLevel)
        ? globalThis.String(object.experienceLevel)
        : isSet(object.experience_level)
        ? globalThis.String(object.experience_level)
        : "",
      skills: globalThis.Array.isArray(object?.skills)
        ? object.skills.map((e: any) => globalThis.String(e))
        : [],
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : false,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: Job): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.postedByUserId !== "") {
      obj.postedByUserId = message.postedByUserId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.salaryRange !== "") {
      obj.salaryRange = message.salaryRange;
    }
    if (message.jobType !== "") {
      obj.jobType = message.jobType;
    }
    if (message.experienceLevel !== "") {
      obj.experienceLevel = message.experienceLevel;
    }
    if (message.skills?.length) {
      obj.skills = message.skills;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Job>, I>>(base?: I): Job {
    return Job.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Job>, I>>(object: I): Job {
    const message = createBaseJob();
    message.id = object.id ?? "";
    message.companyId = object.companyId ?? "";
    message.postedByUserId = object.postedByUserId ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.location = object.location ?? "";
    message.salaryRange = object.salaryRange ?? "";
    message.jobType = object.jobType ?? "";
    message.experienceLevel = object.experienceLevel ?? "";
    message.skills = object.skills?.map((e) => e) || [];
    message.isActive = object.isActive ?? false;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseApplication(): Application {
  return { id: "", jobId: "", userId: "", coverLetter: "", resumeUrl: "", status: "", createdAt: "" };
}

export const Application: MessageFns<Application> = {
  encode(message: Application, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.jobId !== "") {
      writer.uint32(18).string(message.jobId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.coverLetter !== "") {
      writer.uint32(34).string(message.coverLetter);
    }
    if (message.resumeUrl !== "") {
      writer.uint32(42).string(message.resumeUrl);
    }
    if (message.status !== "") {
      writer.uint32(50).string(message.status);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Application {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApplication();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.coverLetter = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.resumeUrl = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Application {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      coverLetter: isSet(object.coverLetter)
        ? globalThis.String(object.coverLetter)
        : isSet(object.cover_letter)
        ? globalThis.String(object.cover_letter)
        : "",
      resumeUrl: isSet(object.resumeUrl)
        ? globalThis.String(object.resumeUrl)
        : isSet(object.resume_url)
        ? globalThis.String(object.resume_url)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
    };
  },

  toJSON(message: Application): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.coverLetter !== "") {
      obj.coverLetter = message.coverLetter;
    }
    if (message.resumeUrl !== "") {
      obj.resumeUrl = message.resumeUrl;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Application>, I>>(base?: I): Application {
    return Application.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Application>, I>>(object: I): Application {
    const message = createBaseApplication();
    message.id = object.id ?? "";
    message.jobId = object.jobId ?? "";
    message.userId = object.userId ?? "";
    message.coverLetter = object.coverLetter ?? "";
    message.resumeUrl = object.resumeUrl ?? "";
    message.status = object.status ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseCreateJobRequest(): CreateJobRequest {
  return {
    companyId: "",
    postedByUserId: "",
    title: "",
    description: "",
    location: "",
    salaryRange: "",
    jobType: "",
    experienceLevel: "",
    skills: [],
  };
}

export const CreateJobRequest: MessageFns<CreateJobRequest> = {
  encode(message: CreateJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.companyId !== "") {
      writer.uint32(10).string(message.companyId);
    }
    if (message.postedByUserId !== "") {
      writer.uint32(18).string(message.postedByUserId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.location !== "") {
      writer.uint32(42).string(message.location);
    }
    if (message.salaryRange !== "") {
      writer.uint32(50).string(message.salaryRange);
    }
    if (message.jobType !== "") {
      writer.uint32(58).string(message.jobType);
    }
    if (message.experienceLevel !== "") {
      writer.uint32(66).string(message.experienceLevel);
    }
    for (const v of message.skills) {
      writer.uint32(74).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.postedByUserId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.salaryRange = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.jobType = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.experienceLevel = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.skills.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateJobRequest {
    return {
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      postedByUserId: isSet(object.postedByUserId)
        ? globalThis.String(object.postedByUserId)
        : isSet(object.posted_by_user_id)
        ? globalThis.String(object.posted_by_user_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      salaryRange: isSet(object.salaryRange)
        ? globalThis.String(object.salaryRange)
        : isSet(object.salary_range)
        ? globalThis.String(object.salary_range)
        : "",
      jobType: isSet(object.jobType)
        ? globalThis.String(object.jobType)
        : isSet(object.job_type)
        ? globalThis.String(object.job_type)
        : "",
      experienceLevel: isSet(object.experienceLevel)
        ? globalThis.String(object.experienceLevel)
        : isSet(object.experience_level)
        ? globalThis.String(object.experience_level)
        : "",
      skills: globalThis.Array.isArray(object?.skills)
        ? object.skills.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CreateJobRequest): unknown {
    const obj: any = {};
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.postedByUserId !== "") {
      obj.postedByUserId = message.postedByUserId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.salaryRange !== "") {
      obj.salaryRange = message.salaryRange;
    }
    if (message.jobType !== "") {
      obj.jobType = message.jobType;
    }
    if (message.experienceLevel !== "") {
      obj.experienceLevel = message.experienceLevel;
    }
    if (message.skills?.length) {
      obj.skills = message.skills;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateJobRequest>, I>>(base?: I): CreateJobRequest {
    return CreateJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateJobRequest>, I>>(object: I): CreateJobRequest {
    const message = createBaseCreateJobRequest();
    message.companyId = object.companyId ?? "";
    message.postedByUserId = object.postedByUserId ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.location = object.location ?? "";
    message.salaryRange = object.salaryRange ?? "";
    message.jobType = object.jobType ?? "";
    message.experienceLevel = object.experienceLevel ?? "";
    message.skills = object.skills?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetJobRequest(): GetJobRequest {
  return { id: "" };
}

export const GetJobRequest: MessageFns<GetJobRequest> = {
  encode(message: GetJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetJobRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetJobRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetJobRequest>, I>>(base?: I): GetJobRequest {
    return GetJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetJobRequest>, I>>(object: I): GetJobRequest {
    const message = createBaseGetJobRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseListJobsRequest(): ListJobsRequest {
  return { page: 0, limit: 0, jobType: "", experienceLevel: "", location: "", postedByUserId: "", companyId: "" };
}

export const ListJobsRequest: MessageFns<ListJobsRequest> = {
  encode(message: ListJobsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.jobType !== "") {
      writer.uint32(26).string(message.jobType);
    }
    if (message.experienceLevel !== "") {
      writer.uint32(34).string(message.experienceLevel);
    }
    if (message.location !== "") {
      writer.uint32(42).string(message.location);
    }
    if (message.postedByUserId !== "") {
      writer.uint32(50).string(message.postedByUserId);
    }
    if (message.companyId !== "") {
      writer.uint32(58).string(message.companyId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListJobsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListJobsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.experienceLevel = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.postedByUserId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListJobsRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      jobType: isSet(object.jobType)
        ? globalThis.String(object.jobType)
        : isSet(object.job_type)
        ? globalThis.String(object.job_type)
        : "",
      experienceLevel: isSet(object.experienceLevel)
        ? globalThis.String(object.experienceLevel)
        : isSet(object.experience_level)
        ? globalThis.String(object.experience_level)
        : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      postedByUserId: isSet(object.postedByUserId)
        ? globalThis.String(object.postedByUserId)
        : isSet(object.posted_by_user_id)
        ? globalThis.String(object.posted_by_user_id)
        : "",
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
    };
  },

  toJSON(message: ListJobsRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.jobType !== "") {
      obj.jobType = message.jobType;
    }
    if (message.experienceLevel !== "") {
      obj.experienceLevel = message.experienceLevel;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.postedByUserId !== "") {
      obj.postedByUserId = message.postedByUserId;
    }
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListJobsRequest>, I>>(base?: I): ListJobsRequest {
    return ListJobsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListJobsRequest>, I>>(object: I): ListJobsRequest {
    const message = createBaseListJobsRequest();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.jobType = object.jobType ?? "";
    message.experienceLevel = object.experienceLevel ?? "";
    message.location = object.location ?? "";
    message.postedByUserId = object.postedByUserId ?? "";
    message.companyId = object.companyId ?? "";
    return message;
  },
};

function createBaseListJobsByCompanyRequest(): ListJobsByCompanyRequest {
  return { companyId: "", page: 0, limit: 0 };
}

export const ListJobsByCompanyRequest: MessageFns<ListJobsByCompanyRequest> = {
  encode(message: ListJobsByCompanyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.companyId !== "") {
      writer.uint32(10).string(message.companyId);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListJobsByCompanyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListJobsByCompanyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.companyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListJobsByCompanyRequest {
    return {
      companyId: isSet(object.companyId)
        ? globalThis.String(object.companyId)
        : isSet(object.company_id)
        ? globalThis.String(object.company_id)
        : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListJobsByCompanyRequest): unknown {
    const obj: any = {};
    if (message.companyId !== "") {
      obj.companyId = message.companyId;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListJobsByCompanyRequest>, I>>(base?: I): ListJobsByCompanyRequest {
    return ListJobsByCompanyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListJobsByCompanyRequest>, I>>(object: I): ListJobsByCompanyRequest {
    const message = createBaseListJobsByCompanyRequest();
    message.companyId = object.companyId ?? "";
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListJobsResponse(): ListJobsResponse {
  return { jobs: [], total: 0 };
}

export const ListJobsResponse: MessageFns<ListJobsResponse> = {
  encode(message: ListJobsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobs) {
      Job.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListJobsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListJobsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobs.push(Job.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListJobsResponse {
    return {
      jobs: globalThis.Array.isArray(object?.jobs) ? object.jobs.map((e: any) => Job.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: ListJobsResponse): unknown {
    const obj: any = {};
    if (message.jobs?.length) {
      obj.jobs = message.jobs.map((e) => Job.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListJobsResponse>, I>>(base?: I): ListJobsResponse {
    return ListJobsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListJobsResponse>, I>>(object: I): ListJobsResponse {
    const message = createBaseListJobsResponse();
    message.jobs = object.jobs?.map((e) => Job.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseUpdateJobRequest(): UpdateJobRequest {
  return {
    id: "",
    title: "",
    description: "",
    location: "",
    salaryRange: "",
    jobType: "",
    experienceLevel: "",
    skills: [],
    isActive: false,
  };
}

export const UpdateJobRequest: MessageFns<UpdateJobRequest> = {
  encode(message: UpdateJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.location !== "") {
      writer.uint32(34).string(message.location);
    }
    if (message.salaryRange !== "") {
      writer.uint32(42).string(message.salaryRange);
    }
    if (message.jobType !== "") {
      writer.uint32(50).string(message.jobType);
    }
    if (message.experienceLevel !== "") {
      writer.uint32(58).string(message.experienceLevel);
    }
    for (const v of message.skills) {
      writer.uint32(66).string(v!);
    }
    if (message.isActive !== false) {
      writer.uint32(72).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.salaryRange = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.jobType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.experienceLevel = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.skills.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateJobRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      salaryRange: isSet(object.salaryRange)
        ? globalThis.String(object.salaryRange)
        : isSet(object.salary_range)
        ? globalThis.String(object.salary_range)
        : "",
      jobType: isSet(object.jobType)
        ? globalThis.String(object.jobType)
        : isSet(object.job_type)
        ? globalThis.String(object.job_type)
        : "",
      experienceLevel: isSet(object.experienceLevel)
        ? globalThis.String(object.experienceLevel)
        : isSet(object.experience_level)
        ? globalThis.String(object.experience_level)
        : "",
      skills: globalThis.Array.isArray(object?.skills)
        ? object.skills.map((e: any) => globalThis.String(e))
        : [],
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : false,
    };
  },

  toJSON(message: UpdateJobRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.salaryRange !== "") {
      obj.salaryRange = message.salaryRange;
    }
    if (message.jobType !== "") {
      obj.jobType = message.jobType;
    }
    if (message.experienceLevel !== "") {
      obj.experienceLevel = message.experienceLevel;
    }
    if (message.skills?.length) {
      obj.skills = message.skills;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateJobRequest>, I>>(base?: I): UpdateJobRequest {
    return UpdateJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateJobRequest>, I>>(object: I): UpdateJobRequest {
    const message = createBaseUpdateJobRequest();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.location = object.location ?? "";
    message.salaryRange = object.salaryRange ?? "";
    message.jobType = object.jobType ?? "";
    message.experienceLevel = object.experienceLevel ?? "";
    message.skills = object.skills?.map((e) => e) || [];
    message.isActive = object.isActive ?? false;
    return message;
  },
};

function createBaseDeleteJobRequest(): DeleteJobRequest {
  return { id: "" };
}

export const DeleteJobRequest: MessageFns<DeleteJobRequest> = {
  encode(message: DeleteJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteJobRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteJobRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteJobRequest>, I>>(base?: I): DeleteJobRequest {
    return DeleteJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteJobRequest>, I>>(object: I): DeleteJobRequest {
    const message = createBaseDeleteJobRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteJobResponse(): DeleteJobResponse {
  return { success: false };
}

export const DeleteJobResponse: MessageFns<DeleteJobResponse> = {
  encode(message: DeleteJobResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteJobResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteJobResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteJobResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeleteJobResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteJobResponse>, I>>(base?: I): DeleteJobResponse {
    return DeleteJobResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteJobResponse>, I>>(object: I): DeleteJobResponse {
    const message = createBaseDeleteJobResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseJobResponse(): JobResponse {
  return { job: undefined };
}

export const JobResponse: MessageFns<JobResponse> = {
  encode(message: JobResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.job !== undefined) {
      Job.encode(message.job, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.job = Job.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobResponse {
    return { job: isSet(object.job) ? Job.fromJSON(object.job) : undefined };
  },

  toJSON(message: JobResponse): unknown {
    const obj: any = {};
    if (message.job !== undefined) {
      obj.job = Job.toJSON(message.job);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobResponse>, I>>(base?: I): JobResponse {
    return JobResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobResponse>, I>>(object: I): JobResponse {
    const message = createBaseJobResponse();
    message.job = (object.job !== undefined && object.job !== null) ? Job.fromPartial(object.job) : undefined;
    return message;
  },
};

function createBaseApplyToJobRequest(): ApplyToJobRequest {
  return { jobId: "", userId: "", coverLetter: "", resumeUrl: "" };
}

export const ApplyToJobRequest: MessageFns<ApplyToJobRequest> = {
  encode(message: ApplyToJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.coverLetter !== "") {
      writer.uint32(26).string(message.coverLetter);
    }
    if (message.resumeUrl !== "") {
      writer.uint32(34).string(message.resumeUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApplyToJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApplyToJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.coverLetter = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resumeUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApplyToJobRequest {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      coverLetter: isSet(object.coverLetter)
        ? globalThis.String(object.coverLetter)
        : isSet(object.cover_letter)
        ? globalThis.String(object.cover_letter)
        : "",
      resumeUrl: isSet(object.resumeUrl)
        ? globalThis.String(object.resumeUrl)
        : isSet(object.resume_url)
        ? globalThis.String(object.resume_url)
        : "",
    };
  },

  toJSON(message: ApplyToJobRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.coverLetter !== "") {
      obj.coverLetter = message.coverLetter;
    }
    if (message.resumeUrl !== "") {
      obj.resumeUrl = message.resumeUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApplyToJobRequest>, I>>(base?: I): ApplyToJobRequest {
    return ApplyToJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApplyToJobRequest>, I>>(object: I): ApplyToJobRequest {
    const message = createBaseApplyToJobRequest();
    message.jobId = object.jobId ?? "";
    message.userId = object.userId ?? "";
    message.coverLetter = object.coverLetter ?? "";
    message.resumeUrl = object.resumeUrl ?? "";
    return message;
  },
};

function createBaseApplicationResponse(): ApplicationResponse {
  return { application: undefined };
}

export const ApplicationResponse: MessageFns<ApplicationResponse> = {
  encode(message: ApplicationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.application !== undefined) {
      Application.encode(message.application, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApplicationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApplicationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.application = Application.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApplicationResponse {
    return { application: isSet(object.application) ? Application.fromJSON(object.application) : undefined };
  },

  toJSON(message: ApplicationResponse): unknown {
    const obj: any = {};
    if (message.application !== undefined) {
      obj.application = Application.toJSON(message.application);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApplicationResponse>, I>>(base?: I): ApplicationResponse {
    return ApplicationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApplicationResponse>, I>>(object: I): ApplicationResponse {
    const message = createBaseApplicationResponse();
    message.application = (object.application !== undefined && object.application !== null)
      ? Application.fromPartial(object.application)
      : undefined;
    return message;
  },
};

function createBaseListApplicationsByJobRequest(): ListApplicationsByJobRequest {
  return { jobId: "", page: 0, limit: 0 };
}

export const ListApplicationsByJobRequest: MessageFns<ListApplicationsByJobRequest> = {
  encode(message: ListApplicationsByJobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListApplicationsByJobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListApplicationsByJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListApplicationsByJobRequest {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListApplicationsByJobRequest): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListApplicationsByJobRequest>, I>>(base?: I): ListApplicationsByJobRequest {
    return ListApplicationsByJobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListApplicationsByJobRequest>, I>>(object: I): ListApplicationsByJobRequest {
    const message = createBaseListApplicationsByJobRequest();
    message.jobId = object.jobId ?? "";
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListApplicationsByUserRequest(): ListApplicationsByUserRequest {
  return { userId: "", page: 0, limit: 0 };
}

export const ListApplicationsByUserRequest: MessageFns<ListApplicationsByUserRequest> = {
  encode(message: ListApplicationsByUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListApplicationsByUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListApplicationsByUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListApplicationsByUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListApplicationsByUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListApplicationsByUserRequest>, I>>(base?: I): ListApplicationsByUserRequest {
    return ListApplicationsByUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListApplicationsByUserRequest>, I>>(
    object: I,
  ): ListApplicationsByUserRequest {
    const message = createBaseListApplicationsByUserRequest();
    message.userId = object.userId ?? "";
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListApplicationsResponse(): ListApplicationsResponse {
  return { applications: [], total: 0 };
}

export const ListApplicationsResponse: MessageFns<ListApplicationsResponse> = {
  encode(message: ListApplicationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.applications) {
      Application.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListApplicationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListApplicationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.applications.push(Application.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListApplicationsResponse {
    return {
      applications: globalThis.Array.isArray(object?.applications)
        ? object.applications.map((e: any) => Application.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: ListApplicationsResponse): unknown {
    const obj: any = {};
    if (message.applications?.length) {
      obj.applications = message.applications.map((e) => Application.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListApplicationsResponse>, I>>(base?: I): ListApplicationsResponse {
    return ListApplicationsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListApplicationsResponse>, I>>(object: I): ListApplicationsResponse {
    const message = createBaseListApplicationsResponse();
    message.applications = object.applications?.map((e) => Application.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

export type JobServiceService = typeof JobServiceService;
export const JobServiceService = {
  createJob: {
    path: "/job.JobService/CreateJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateJobRequest): Buffer => Buffer.from(CreateJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateJobRequest => CreateJobRequest.decode(value),
    responseSerialize: (value: JobResponse): Buffer => Buffer.from(JobResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobResponse => JobResponse.decode(value),
  },
  getJob: {
    path: "/job.JobService/GetJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetJobRequest): Buffer => Buffer.from(GetJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetJobRequest => GetJobRequest.decode(value),
    responseSerialize: (value: JobResponse): Buffer => Buffer.from(JobResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobResponse => JobResponse.decode(value),
  },
  listJobs: {
    path: "/job.JobService/ListJobs" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListJobsRequest): Buffer => Buffer.from(ListJobsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListJobsRequest => ListJobsRequest.decode(value),
    responseSerialize: (value: ListJobsResponse): Buffer => Buffer.from(ListJobsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListJobsResponse => ListJobsResponse.decode(value),
  },
  updateJob: {
    path: "/job.JobService/UpdateJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateJobRequest): Buffer => Buffer.from(UpdateJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateJobRequest => UpdateJobRequest.decode(value),
    responseSerialize: (value: JobResponse): Buffer => Buffer.from(JobResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobResponse => JobResponse.decode(value),
  },
  deleteJob: {
    path: "/job.JobService/DeleteJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteJobRequest): Buffer => Buffer.from(DeleteJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteJobRequest => DeleteJobRequest.decode(value),
    responseSerialize: (value: DeleteJobResponse): Buffer => Buffer.from(DeleteJobResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteJobResponse => DeleteJobResponse.decode(value),
  },
  listJobsByCompany: {
    path: "/job.JobService/ListJobsByCompany" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListJobsByCompanyRequest): Buffer =>
      Buffer.from(ListJobsByCompanyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListJobsByCompanyRequest => ListJobsByCompanyRequest.decode(value),
    responseSerialize: (value: ListJobsResponse): Buffer => Buffer.from(ListJobsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListJobsResponse => ListJobsResponse.decode(value),
  },
  applyToJob: {
    path: "/job.JobService/ApplyToJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ApplyToJobRequest): Buffer => Buffer.from(ApplyToJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ApplyToJobRequest => ApplyToJobRequest.decode(value),
    responseSerialize: (value: ApplicationResponse): Buffer => Buffer.from(ApplicationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ApplicationResponse => ApplicationResponse.decode(value),
  },
  listApplicationsByJob: {
    path: "/job.JobService/ListApplicationsByJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListApplicationsByJobRequest): Buffer =>
      Buffer.from(ListApplicationsByJobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListApplicationsByJobRequest => ListApplicationsByJobRequest.decode(value),
    responseSerialize: (value: ListApplicationsResponse): Buffer =>
      Buffer.from(ListApplicationsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListApplicationsResponse => ListApplicationsResponse.decode(value),
  },
  listApplicationsByUser: {
    path: "/job.JobService/ListApplicationsByUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListApplicationsByUserRequest): Buffer =>
      Buffer.from(ListApplicationsByUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListApplicationsByUserRequest => ListApplicationsByUserRequest.decode(value),
    responseSerialize: (value: ListApplicationsResponse): Buffer =>
      Buffer.from(ListApplicationsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListApplicationsResponse => ListApplicationsResponse.decode(value),
  },
} as const;

export interface JobServiceServer extends UntypedServiceImplementation {
  createJob: handleUnaryCall<CreateJobRequest, JobResponse>;
  getJob: handleUnaryCall<GetJobRequest, JobResponse>;
  listJobs: handleUnaryCall<ListJobsRequest, ListJobsResponse>;
  updateJob: handleUnaryCall<UpdateJobRequest, JobResponse>;
  deleteJob: handleUnaryCall<DeleteJobRequest, DeleteJobResponse>;
  listJobsByCompany: handleUnaryCall<ListJobsByCompanyRequest, ListJobsResponse>;
  applyToJob: handleUnaryCall<ApplyToJobRequest, ApplicationResponse>;
  listApplicationsByJob: handleUnaryCall<ListApplicationsByJobRequest, ListApplicationsResponse>;
  listApplicationsByUser: handleUnaryCall<ListApplicationsByUserRequest, ListApplicationsResponse>;
}

export interface JobServiceClient extends Client {
  createJob(
    request: CreateJobRequest,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  createJob(
    request: CreateJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  createJob(
    request: CreateJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  getJob(
    request: GetJobRequest,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  getJob(
    request: GetJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  getJob(
    request: GetJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  listJobs(
    request: ListJobsRequest,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  listJobs(
    request: ListJobsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  listJobs(
    request: ListJobsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  updateJob(
    request: UpdateJobRequest,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  updateJob(
    request: UpdateJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  updateJob(
    request: UpdateJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobResponse) => void,
  ): ClientUnaryCall;
  deleteJob(
    request: DeleteJobRequest,
    callback: (error: ServiceError | null, response: DeleteJobResponse) => void,
  ): ClientUnaryCall;
  deleteJob(
    request: DeleteJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DeleteJobResponse) => void,
  ): ClientUnaryCall;
  deleteJob(
    request: DeleteJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DeleteJobResponse) => void,
  ): ClientUnaryCall;
  listJobsByCompany(
    request: ListJobsByCompanyRequest,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  listJobsByCompany(
    request: ListJobsByCompanyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  listJobsByCompany(
    request: ListJobsByCompanyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListJobsResponse) => void,
  ): ClientUnaryCall;
  applyToJob(
    request: ApplyToJobRequest,
    callback: (error: ServiceError | null, response: ApplicationResponse) => void,
  ): ClientUnaryCall;
  applyToJob(
    request: ApplyToJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ApplicationResponse) => void,
  ): ClientUnaryCall;
  applyToJob(
    request: ApplyToJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ApplicationResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByJob(
    request: ListApplicationsByJobRequest,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByJob(
    request: ListApplicationsByJobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByJob(
    request: ListApplicationsByJobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByUser(
    request: ListApplicationsByUserRequest,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByUser(
    request: ListApplicationsByUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
  listApplicationsByUser(
    request: ListApplicationsByUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListApplicationsResponse) => void,
  ): ClientUnaryCall;
}

export const JobServiceClient = makeGenericClientConstructor(JobServiceService, "job.JobService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): JobServiceClient;
  service: typeof JobServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
