// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: subscription.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "subscription";

export interface Subscription {
  id: string;
  userId: string;
  /** TALENT_HUNTER_FREE, TALENT_HUNTER_PRO, JOB_HUNTER_FREE, JOB_HUNTER_PRO */
  plan: string;
  price: number;
  /** ACTIVE, CANCELLED, EXPIRED */
  status: string;
  startsAt: string;
  endsAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Usage {
  id: string;
  userId: string;
  /** JOB_POST, JOB_APPLY */
  actionType: string;
  usedCount: number;
  /** -1 = unlimited */
  maxCount: number;
  periodStart: string;
  periodEnd: string;
}

export interface CreateSubscriptionRequest {
  userId: string;
  plan: string;
}

export interface GetSubscriptionRequest {
  id: string;
}

export interface GetSubscriptionByUserRequest {
  userId: string;
}

export interface CancelSubscriptionRequest {
  id: string;
}

export interface SubscriptionResponse {
  subscription: Subscription | undefined;
}

export interface CheckUsageLimitRequest {
  userId: string;
  actionType: string;
}

export interface CheckUsageLimitResponse {
  allowed: boolean;
  usedCount: number;
  maxCount: number;
}

export interface IncrementUsageRequest {
  userId: string;
  actionType: string;
}

export interface UsageResponse {
  usage: Usage | undefined;
}

export interface GetUsageRequest {
  userId: string;
  actionType: string;
}

function createBaseSubscription(): Subscription {
  return { id: "", userId: "", plan: "", price: 0, status: "", startsAt: "", endsAt: "", createdAt: "", updatedAt: "" };
}

export const Subscription: MessageFns<Subscription> = {
  encode(message: Subscription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.plan !== "") {
      writer.uint32(26).string(message.plan);
    }
    if (message.price !== 0) {
      writer.uint32(33).double(message.price);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.startsAt !== "") {
      writer.uint32(50).string(message.startsAt);
    }
    if (message.endsAt !== "") {
      writer.uint32(58).string(message.endsAt);
    }
    if (message.createdAt !== "") {
      writer.uint32(66).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(74).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Subscription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.plan = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.startsAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.endsAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscription {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      plan: isSet(object.plan) ? globalThis.String(object.plan) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      startsAt: isSet(object.startsAt)
        ? globalThis.String(object.startsAt)
        : isSet(object.starts_at)
        ? globalThis.String(object.starts_at)
        : "",
      endsAt: isSet(object.endsAt)
        ? globalThis.String(object.endsAt)
        : isSet(object.ends_at)
        ? globalThis.String(object.ends_at)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: Subscription): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.plan !== "") {
      obj.plan = message.plan;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.startsAt !== "") {
      obj.startsAt = message.startsAt;
    }
    if (message.endsAt !== "") {
      obj.endsAt = message.endsAt;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscription>, I>>(base?: I): Subscription {
    return Subscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscription>, I>>(object: I): Subscription {
    const message = createBaseSubscription();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.plan = object.plan ?? "";
    message.price = object.price ?? 0;
    message.status = object.status ?? "";
    message.startsAt = object.startsAt ?? "";
    message.endsAt = object.endsAt ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseUsage(): Usage {
  return { id: "", userId: "", actionType: "", usedCount: 0, maxCount: 0, periodStart: "", periodEnd: "" };
}

export const Usage: MessageFns<Usage> = {
  encode(message: Usage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.actionType !== "") {
      writer.uint32(26).string(message.actionType);
    }
    if (message.usedCount !== 0) {
      writer.uint32(32).int32(message.usedCount);
    }
    if (message.maxCount !== 0) {
      writer.uint32(40).int32(message.maxCount);
    }
    if (message.periodStart !== "") {
      writer.uint32(50).string(message.periodStart);
    }
    if (message.periodEnd !== "") {
      writer.uint32(58).string(message.periodEnd);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Usage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.usedCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxCount = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.periodStart = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.periodEnd = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Usage {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      actionType: isSet(object.actionType)
        ? globalThis.String(object.actionType)
        : isSet(object.action_type)
        ? globalThis.String(object.action_type)
        : "",
      usedCount: isSet(object.usedCount)
        ? globalThis.Number(object.usedCount)
        : isSet(object.used_count)
        ? globalThis.Number(object.used_count)
        : 0,
      maxCount: isSet(object.maxCount)
        ? globalThis.Number(object.maxCount)
        : isSet(object.max_count)
        ? globalThis.Number(object.max_count)
        : 0,
      periodStart: isSet(object.periodStart)
        ? globalThis.String(object.periodStart)
        : isSet(object.period_start)
        ? globalThis.String(object.period_start)
        : "",
      periodEnd: isSet(object.periodEnd)
        ? globalThis.String(object.periodEnd)
        : isSet(object.period_end)
        ? globalThis.String(object.period_end)
        : "",
    };
  },

  toJSON(message: Usage): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.actionType !== "") {
      obj.actionType = message.actionType;
    }
    if (message.usedCount !== 0) {
      obj.usedCount = Math.round(message.usedCount);
    }
    if (message.maxCount !== 0) {
      obj.maxCount = Math.round(message.maxCount);
    }
    if (message.periodStart !== "") {
      obj.periodStart = message.periodStart;
    }
    if (message.periodEnd !== "") {
      obj.periodEnd = message.periodEnd;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Usage>, I>>(base?: I): Usage {
    return Usage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Usage>, I>>(object: I): Usage {
    const message = createBaseUsage();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.actionType = object.actionType ?? "";
    message.usedCount = object.usedCount ?? 0;
    message.maxCount = object.maxCount ?? 0;
    message.periodStart = object.periodStart ?? "";
    message.periodEnd = object.periodEnd ?? "";
    return message;
  },
};

function createBaseCreateSubscriptionRequest(): CreateSubscriptionRequest {
  return { userId: "", plan: "" };
}

export const CreateSubscriptionRequest: MessageFns<CreateSubscriptionRequest> = {
  encode(message: CreateSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.plan !== "") {
      writer.uint32(18).string(message.plan);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.plan = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSubscriptionRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      plan: isSet(object.plan) ? globalThis.String(object.plan) : "",
    };
  },

  toJSON(message: CreateSubscriptionRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.plan !== "") {
      obj.plan = message.plan;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSubscriptionRequest>, I>>(base?: I): CreateSubscriptionRequest {
    return CreateSubscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSubscriptionRequest>, I>>(object: I): CreateSubscriptionRequest {
    const message = createBaseCreateSubscriptionRequest();
    message.userId = object.userId ?? "";
    message.plan = object.plan ?? "";
    return message;
  },
};

function createBaseGetSubscriptionRequest(): GetSubscriptionRequest {
  return { id: "" };
}

export const GetSubscriptionRequest: MessageFns<GetSubscriptionRequest> = {
  encode(message: GetSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSubscriptionRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetSubscriptionRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSubscriptionRequest>, I>>(base?: I): GetSubscriptionRequest {
    return GetSubscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSubscriptionRequest>, I>>(object: I): GetSubscriptionRequest {
    const message = createBaseGetSubscriptionRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetSubscriptionByUserRequest(): GetSubscriptionByUserRequest {
  return { userId: "" };
}

export const GetSubscriptionByUserRequest: MessageFns<GetSubscriptionByUserRequest> = {
  encode(message: GetSubscriptionByUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionByUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionByUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSubscriptionByUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: GetSubscriptionByUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSubscriptionByUserRequest>, I>>(base?: I): GetSubscriptionByUserRequest {
    return GetSubscriptionByUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSubscriptionByUserRequest>, I>>(object: I): GetSubscriptionByUserRequest {
    const message = createBaseGetSubscriptionByUserRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseCancelSubscriptionRequest(): CancelSubscriptionRequest {
  return { id: "" };
}

export const CancelSubscriptionRequest: MessageFns<CancelSubscriptionRequest> = {
  encode(message: CancelSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelSubscriptionRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: CancelSubscriptionRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelSubscriptionRequest>, I>>(base?: I): CancelSubscriptionRequest {
    return CancelSubscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelSubscriptionRequest>, I>>(object: I): CancelSubscriptionRequest {
    const message = createBaseCancelSubscriptionRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseSubscriptionResponse(): SubscriptionResponse {
  return { subscription: undefined };
}

export const SubscriptionResponse: MessageFns<SubscriptionResponse> = {
  encode(message: SubscriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscription !== undefined) {
      Subscription.encode(message.subscription, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscription = Subscription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscriptionResponse {
    return { subscription: isSet(object.subscription) ? Subscription.fromJSON(object.subscription) : undefined };
  },

  toJSON(message: SubscriptionResponse): unknown {
    const obj: any = {};
    if (message.subscription !== undefined) {
      obj.subscription = Subscription.toJSON(message.subscription);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscriptionResponse>, I>>(base?: I): SubscriptionResponse {
    return SubscriptionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscriptionResponse>, I>>(object: I): SubscriptionResponse {
    const message = createBaseSubscriptionResponse();
    message.subscription = (object.subscription !== undefined && object.subscription !== null)
      ? Subscription.fromPartial(object.subscription)
      : undefined;
    return message;
  },
};

function createBaseCheckUsageLimitRequest(): CheckUsageLimitRequest {
  return { userId: "", actionType: "" };
}

export const CheckUsageLimitRequest: MessageFns<CheckUsageLimitRequest> = {
  encode(message: CheckUsageLimitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.actionType !== "") {
      writer.uint32(18).string(message.actionType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckUsageLimitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckUsageLimitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actionType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckUsageLimitRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      actionType: isSet(object.actionType)
        ? globalThis.String(object.actionType)
        : isSet(object.action_type)
        ? globalThis.String(object.action_type)
        : "",
    };
  },

  toJSON(message: CheckUsageLimitRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.actionType !== "") {
      obj.actionType = message.actionType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckUsageLimitRequest>, I>>(base?: I): CheckUsageLimitRequest {
    return CheckUsageLimitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckUsageLimitRequest>, I>>(object: I): CheckUsageLimitRequest {
    const message = createBaseCheckUsageLimitRequest();
    message.userId = object.userId ?? "";
    message.actionType = object.actionType ?? "";
    return message;
  },
};

function createBaseCheckUsageLimitResponse(): CheckUsageLimitResponse {
  return { allowed: false, usedCount: 0, maxCount: 0 };
}

export const CheckUsageLimitResponse: MessageFns<CheckUsageLimitResponse> = {
  encode(message: CheckUsageLimitResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowed !== false) {
      writer.uint32(8).bool(message.allowed);
    }
    if (message.usedCount !== 0) {
      writer.uint32(16).int32(message.usedCount);
    }
    if (message.maxCount !== 0) {
      writer.uint32(24).int32(message.maxCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckUsageLimitResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckUsageLimitResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.allowed = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.usedCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckUsageLimitResponse {
    return {
      allowed: isSet(object.allowed) ? globalThis.Boolean(object.allowed) : false,
      usedCount: isSet(object.usedCount)
        ? globalThis.Number(object.usedCount)
        : isSet(object.used_count)
        ? globalThis.Number(object.used_count)
        : 0,
      maxCount: isSet(object.maxCount)
        ? globalThis.Number(object.maxCount)
        : isSet(object.max_count)
        ? globalThis.Number(object.max_count)
        : 0,
    };
  },

  toJSON(message: CheckUsageLimitResponse): unknown {
    const obj: any = {};
    if (message.allowed !== false) {
      obj.allowed = message.allowed;
    }
    if (message.usedCount !== 0) {
      obj.usedCount = Math.round(message.usedCount);
    }
    if (message.maxCount !== 0) {
      obj.maxCount = Math.round(message.maxCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckUsageLimitResponse>, I>>(base?: I): CheckUsageLimitResponse {
    return CheckUsageLimitResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckUsageLimitResponse>, I>>(object: I): CheckUsageLimitResponse {
    const message = createBaseCheckUsageLimitResponse();
    message.allowed = object.allowed ?? false;
    message.usedCount = object.usedCount ?? 0;
    message.maxCount = object.maxCount ?? 0;
    return message;
  },
};

function createBaseIncrementUsageRequest(): IncrementUsageRequest {
  return { userId: "", actionType: "" };
}

export const IncrementUsageRequest: MessageFns<IncrementUsageRequest> = {
  encode(message: IncrementUsageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.actionType !== "") {
      writer.uint32(18).string(message.actionType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncrementUsageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncrementUsageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actionType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IncrementUsageRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      actionType: isSet(object.actionType)
        ? globalThis.String(object.actionType)
        : isSet(object.action_type)
        ? globalThis.String(object.action_type)
        : "",
    };
  },

  toJSON(message: IncrementUsageRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.actionType !== "") {
      obj.actionType = message.actionType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IncrementUsageRequest>, I>>(base?: I): IncrementUsageRequest {
    return IncrementUsageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IncrementUsageRequest>, I>>(object: I): IncrementUsageRequest {
    const message = createBaseIncrementUsageRequest();
    message.userId = object.userId ?? "";
    message.actionType = object.actionType ?? "";
    return message;
  },
};

function createBaseUsageResponse(): UsageResponse {
  return { usage: undefined };
}

export const UsageResponse: MessageFns<UsageResponse> = {
  encode(message: UsageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.usage !== undefined) {
      Usage.encode(message.usage, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UsageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.usage = Usage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UsageResponse {
    return { usage: isSet(object.usage) ? Usage.fromJSON(object.usage) : undefined };
  },

  toJSON(message: UsageResponse): unknown {
    const obj: any = {};
    if (message.usage !== undefined) {
      obj.usage = Usage.toJSON(message.usage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UsageResponse>, I>>(base?: I): UsageResponse {
    return UsageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UsageResponse>, I>>(object: I): UsageResponse {
    const message = createBaseUsageResponse();
    message.usage = (object.usage !== undefined && object.usage !== null) ? Usage.fromPartial(object.usage) : undefined;
    return message;
  },
};

function createBaseGetUsageRequest(): GetUsageRequest {
  return { userId: "", actionType: "" };
}

export const GetUsageRequest: MessageFns<GetUsageRequest> = {
  encode(message: GetUsageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.actionType !== "") {
      writer.uint32(18).string(message.actionType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actionType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUsageRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      actionType: isSet(object.actionType)
        ? globalThis.String(object.actionType)
        : isSet(object.action_type)
        ? globalThis.String(object.action_type)
        : "",
    };
  },

  toJSON(message: GetUsageRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.actionType !== "") {
      obj.actionType = message.actionType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUsageRequest>, I>>(base?: I): GetUsageRequest {
    return GetUsageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUsageRequest>, I>>(object: I): GetUsageRequest {
    const message = createBaseGetUsageRequest();
    message.userId = object.userId ?? "";
    message.actionType = object.actionType ?? "";
    return message;
  },
};

export type SubscriptionServiceService = typeof SubscriptionServiceService;
export const SubscriptionServiceService = {
  createSubscription: {
    path: "/subscription.SubscriptionService/CreateSubscription" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateSubscriptionRequest): Buffer =>
      Buffer.from(CreateSubscriptionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateSubscriptionRequest => CreateSubscriptionRequest.decode(value),
    responseSerialize: (value: SubscriptionResponse): Buffer =>
      Buffer.from(SubscriptionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscriptionResponse => SubscriptionResponse.decode(value),
  },
  getSubscription: {
    path: "/subscription.SubscriptionService/GetSubscription" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSubscriptionRequest): Buffer =>
      Buffer.from(GetSubscriptionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSubscriptionRequest => GetSubscriptionRequest.decode(value),
    responseSerialize: (value: SubscriptionResponse): Buffer =>
      Buffer.from(SubscriptionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscriptionResponse => SubscriptionResponse.decode(value),
  },
  getSubscriptionByUser: {
    path: "/subscription.SubscriptionService/GetSubscriptionByUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSubscriptionByUserRequest): Buffer =>
      Buffer.from(GetSubscriptionByUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSubscriptionByUserRequest => GetSubscriptionByUserRequest.decode(value),
    responseSerialize: (value: SubscriptionResponse): Buffer =>
      Buffer.from(SubscriptionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscriptionResponse => SubscriptionResponse.decode(value),
  },
  cancelSubscription: {
    path: "/subscription.SubscriptionService/CancelSubscription" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CancelSubscriptionRequest): Buffer =>
      Buffer.from(CancelSubscriptionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CancelSubscriptionRequest => CancelSubscriptionRequest.decode(value),
    responseSerialize: (value: SubscriptionResponse): Buffer =>
      Buffer.from(SubscriptionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscriptionResponse => SubscriptionResponse.decode(value),
  },
  checkUsageLimit: {
    path: "/subscription.SubscriptionService/CheckUsageLimit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckUsageLimitRequest): Buffer =>
      Buffer.from(CheckUsageLimitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckUsageLimitRequest => CheckUsageLimitRequest.decode(value),
    responseSerialize: (value: CheckUsageLimitResponse): Buffer =>
      Buffer.from(CheckUsageLimitResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckUsageLimitResponse => CheckUsageLimitResponse.decode(value),
  },
  incrementUsage: {
    path: "/subscription.SubscriptionService/IncrementUsage" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: IncrementUsageRequest): Buffer =>
      Buffer.from(IncrementUsageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): IncrementUsageRequest => IncrementUsageRequest.decode(value),
    responseSerialize: (value: UsageResponse): Buffer => Buffer.from(UsageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UsageResponse => UsageResponse.decode(value),
  },
  getUsage: {
    path: "/subscription.SubscriptionService/GetUsage" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUsageRequest): Buffer => Buffer.from(GetUsageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsageRequest => GetUsageRequest.decode(value),
    responseSerialize: (value: UsageResponse): Buffer => Buffer.from(UsageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UsageResponse => UsageResponse.decode(value),
  },
} as const;

export interface SubscriptionServiceServer extends UntypedServiceImplementation {
  createSubscription: handleUnaryCall<CreateSubscriptionRequest, SubscriptionResponse>;
  getSubscription: handleUnaryCall<GetSubscriptionRequest, SubscriptionResponse>;
  getSubscriptionByUser: handleUnaryCall<GetSubscriptionByUserRequest, SubscriptionResponse>;
  cancelSubscription: handleUnaryCall<CancelSubscriptionRequest, SubscriptionResponse>;
  checkUsageLimit: handleUnaryCall<CheckUsageLimitRequest, CheckUsageLimitResponse>;
  incrementUsage: handleUnaryCall<IncrementUsageRequest, UsageResponse>;
  getUsage: handleUnaryCall<GetUsageRequest, UsageResponse>;
}

export interface SubscriptionServiceClient extends Client {
  createSubscription(
    request: CreateSubscriptionRequest,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  createSubscription(
    request: CreateSubscriptionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  createSubscription(
    request: CreateSubscriptionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscription(
    request: GetSubscriptionRequest,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscription(
    request: GetSubscriptionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscription(
    request: GetSubscriptionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscriptionByUser(
    request: GetSubscriptionByUserRequest,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscriptionByUser(
    request: GetSubscriptionByUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscriptionByUser(
    request: GetSubscriptionByUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  cancelSubscription(
    request: CancelSubscriptionRequest,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  cancelSubscription(
    request: CancelSubscriptionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  cancelSubscription(
    request: CancelSubscriptionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  checkUsageLimit(
    request: CheckUsageLimitRequest,
    callback: (error: ServiceError | null, response: CheckUsageLimitResponse) => void,
  ): ClientUnaryCall;
  checkUsageLimit(
    request: CheckUsageLimitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckUsageLimitResponse) => void,
  ): ClientUnaryCall;
  checkUsageLimit(
    request: CheckUsageLimitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckUsageLimitResponse) => void,
  ): ClientUnaryCall;
  incrementUsage(
    request: IncrementUsageRequest,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
  incrementUsage(
    request: IncrementUsageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
  incrementUsage(
    request: IncrementUsageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UsageResponse) => void,
  ): ClientUnaryCall;
}

export const SubscriptionServiceClient = makeGenericClientConstructor(
  SubscriptionServiceService,
  "subscription.SubscriptionService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SubscriptionServiceClient;
  service: typeof SubscriptionServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
