server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /graphql {
        proxy_pass http://graphql-bff:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /upload {
        proxy_pass http://document-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 6m;
    }

    location /documents/ {
        proxy_pass http://document-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
